CREATE DATABASE IF NOT EXISTS factura_countdown;
USE factura_countdown;
CREATE TABLE IF NOT EXISTS users (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150),
lastname VARCHAR(150),
email VARCHAR(150),
date_birthday DATE,
description NVARCHAR(600),
phone VARCHAR(14),
last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DESCRIBE users;